[book]
authors = ["Jonathan Kurtz"]
language = "en"
src = "src"
title = "RocDocs: L2"

[output.html]
theme = "../../theme"
additional-css = ["../../static/custom.css"]
additional-js = ["../../static/version-switch.js"]
