[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
mdbook-driver = "0.5.2"
mdbook-html = "0.5.2"
warp = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
