[book]
title = "Team"
authors = ["Jonathan Kurtz"]
language = "en"

[output.html]
theme = "../../theme"
additional-css = ["../../static/custom.css"]
additional-js = ["../../static/version-switch.js"]
